### ISSUE TITLE
How do you measure logging timmings?

### ISSUE THREAD

**Issue by Kikobeats** [mcollina/the-cost-of-logging#2]
<img width="458" alt="screen shot 2016-07-28 at 23 50 26" src="https://cloud.githubusercontent.com/assets/2096101/17230697/1121f752-551e-11e6-9a08-00b7c1800046.png">

I one to be part of this benchmark, just for curiosity, with my [acho](https://github.com/achohq/acho) logger 😄

**Comment by davidmarkclements** [comment]
@Kikobeats check out https://github.com/mcollina/pino/tree/master/benchmarks 

The graph is based on raw numbers from those benchmarks, we use the fastbench module to run the benchmarks

**Comment by Kikobeats** [comment]
Thanks!
